### PR TITLE
Allow for block-comment-style frontmatter for SQL files

### PR DESCRIPTION
**Pull request by josh-fell**
This PR is a proposal to allow users to declare their frontmatter with a block comment (i.e. `/* ... */`).

Some users may feel this is an intuitive approach when operating solely in SQL files as block comments are widely supported. Also, this allows for SQL to be more easily linted out-of-the-box with tools like SQLFluff without requiring custom plugins or placeholder workarounds to address both the templating _and_ the current `---` frontmatter pattern.

### CODE REVIEW

**Comment by josh-fell** [comment]
I'm not entirely sure what happened with CI here, but I'll close and reopen to re-trigger. Perhaps some random flakiness?

**Comment by chriscardillo** [comment]
Thanks for this. I am not sure what's going on with CI either, but we will land this in a branch for v0.5.0 and I will handle getting it to main/release from there. I ran your branch tests locally with success.

I appreciate the thoroughness of the tests. My questions would be:

- If we kept all of the tests and new test files, would it be cleaner to have the pattern of, for example, `tests/files/constructor/dashes.sql` and `tests/files/constructor/blocks.sql`, then parameterize tests on `tests/files/constructor/*` instead?

- If we limited tests to just what illustrates the new functionality, might [multi_block_comment.sql](https://github.com/josh-fell/ABSQL/blob/block-comment-frontmatter/tests/files/multi_block_comment.sql) and the [test_render_simple_sql_with_multiple_block_comments](https://github.com/josh-fell/ABSQL/blob/ce2358136705b2b9a3249dae5988246428005434/tests/test_render_file.py#L48-L53) test be enough to cover both the new feature and the case of multiple block comments in a file? As proven by your work, parsing the block comments as frontmatter will not affect the rendering of the frontmatter, so you really only need to test that the file parses, and for that one "integration" test (`test_render_simple_sql_with_multiple_block_comments`) should suffice, no?

**Comment by josh-fell** [comment]
> Thanks for this. I am not sure what's going on with CI either, but we will land this in a branch for v0.5.0 and I will handle getting it to main/release from there. I ran your branch tests locally with success.
> 
> I appreciate the thoroughness of the tests. My questions would be:
> 
>     * If we kept all of the tests and new test files, would it be cleaner to have the pattern of, for example, `tests/files/constructor/dashes.sql` and `tests/files/constructor/blocks.sql`, then parameterize tests on `tests/files/constructor/*` instead?
> 
>     * If we limited tests to just what illustrates the new functionality, might [multi_block_comment.sql](https://github.com/josh-fell/ABSQL/blob/block-comment-frontmatter/tests/files/multi_block_comment.sql) and the [test_render_simple_sql_with_multiple_block_comments](https://github.com/josh-fell/ABSQL/blob/ce2358136705b2b9a3249dae5988246428005434/tests/test_render_file.py#L48-L53) test be enough to cover both the new feature and the case of multiple block comments in a file? As proven by your work, parsing the block comments as frontmatter will not affect the rendering of the frontmatter, so you really only need to test that the file parses, and for that one "integration" test (`test_render_simple_sql_with_multiple_block_comments`) should suffice, no?

Completely fair. I may have gone "overboard" on the tests simply to keep up with the different flavors of files that already existed. But, I'm with you, I can cut down the tests and only target new functionality. Let's go with the 2nd option you outlined.

**Comment by josh-fell** [comment]
Reduced in the testing-related changes as part of https://github.com/pipeline-tools/ABSQL/pull/5/commits/49cf7d0486d4467ea869dc3c6672d9276b307dfe

**Review by chriscardillo — APPROVED** [review]

**Pull request merged**
